### ISSUE TITLE
Several issues when deploying an app with Distillery

### ISSUE THREAD

**Issue by sobolevn** [samueljseay/recaptcha#14]
I have faced some issues when trying to deploy my app with the `recaptcha` dependency in it.

I have almost fixed all of them, here's the list:
1. No `:build_embedded` and `:start_permanent`
2. Distillery does not work with `System.get_env` (docs: https://hexdocs.pm/distillery/runtime-configuration.html#content)

Here's an article about it: https://virviil.github.io/2016/11/30/Elixir-You-package-should-survive-in-production.html

So, the PR is coming.

**Comment by samueljseay** [comment]
Hey, not sure why I seem to be missing github notifications, but thank you for looking at this. I've been a bit busy with non-Elixir things at the moment so a PR would be greatly appreciated :)

**Comment by samueljseay** [comment]
Actually @sobolevn didn't this PR address the configuration issues: https://github.com/samueljseay/recaptcha/pull/13

You should be able to use the last style to configure at runtime?
