### ISSUE TITLE
Suggested Improvements

### ISSUE THREAD

**Issue by samueljseay** [samueljseay/recaptcha#2]
Hi,

Picked up this lib today to use and its great thanks for putting it together 😄 

I was just wondering if perhaps you'd be interested in a PR with adjustments to the API, that in my mind sit a little closer to Elixir idioms.

A couple things I'd love to change:

1. It'd be great if there were a `verify!` and a `verify` with `verify!` being the only method call that raises an exception. I don't really ever want to raise exceptions, but rather receive errors from the API and deal with them.

2. I'd love if the return from `verify` was a bit more idiomatic returning a tuple like:

```
# success, with response being the json returned by googles api
{:ok, response} 

# error, contains all the specific error messages, let the user of the API handle them as they wish
{:error, errors}
```

thoughts?

**Comment by JustMikey** [comment]
@samueljseay  Hi, thanks for the interest and I think it makes sense. PR is rather welcome but I think I need to make this package a bit more decent first (add docs, rewrite some things and etc) and then we could do what you are offering :)

**Comment by JustMikey** [comment]
@samueljseay I have created a new branch (v2) with new api, what do you think about it? It doesn't have a bang version yet but it's easy to add and the verification function returns the response from the google api as a map so you'd have a complete control over it. Do you think it's okay this way?

**Comment by samueljseay** [comment]
@JustMikey thats looking good. My only suggestion would be I'd still be keen for it to differentiate between :ok and :error

it makes a workflow scenario using `with` much simpler

for example:

```
# Elixir 1.3 with/else (but principle is still the same without else)
  with {:ok, response} <- Recaptcha.verify(...),
         {:ok, _whatever} <- #next step in workflow
  else
         {:error, %{ "error-codes" => errors }} -> #do something with errors here
  end
```

thoughts?

**Comment by JustMikey** [comment]
@samueljseay Check out the last commit please. Do you like it?

**Comment by samueljseay** [comment]
Awesome 😄 looks good!

**Comment by samueljseay** [comment]
@JustMikey ping, any chance of movement on this?

**Comment by samueljseay** [comment]
Closing this issue in favour of #6
