### ISSUE TITLE
Missing required parameters: sitekey

### ISSUE THREAD

**Issue by denispeplin** [samueljseay/recaptcha#22]
After adding `recaptcha` to my page I'm getting this error:

```
recaptcha__en.js:382 Uncaught Error: Missing required parameters: sitekey
```

**Comment by sobolevn** [comment]
Did you configure and restart your server?

```elixir
config :recaptcha,
    public_key: "Your public key",
    secret: "Your secret key"
```

**Comment by denispeplin** [comment]
Yes, placed this config into dev.exs, server restarted.

**Comment by denispeplin** [comment]
Btw, I created a fork, because I can't install `recaptcha` into my Phoenix 1.3 application: https://github.com/denispeplin/recaptcha/commit/d1208df56d7f4194cbb86fc5852a412c404610a8

Could be this a source of the problem?

**Comment by sobolevn** [comment]
Yes, it may be the cause. Could you send a PR with this change?

**Comment by denispeplin** [comment]
Done.

**Comment by sobolevn** [comment]
Thanks!

**Comment by denispeplin** [comment]
I still have same issue.

**Comment by denispeplin** [comment]
I found the source of the issue. I was using config from README:

```elixir
config :recaptcha,
   public_key: {:system, "RECAPTCHA_PUBLIC_KEY"},
  secret: {:system, "RECAPTCHA_PRIVATE_KEY"}
```

And with config you've provided above the error disappeared.

**Comment by sobolevn** [comment]
Ok, I will fix it right away.

**Comment by sobolevn** [comment]
It is working for me:

> » RECAPTCHA_PRIVATE_KEY=some MIX_ENV=dev iex -S mix
> Erlang/OTP 19 [erts-8.2.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
> 
> Interactive Elixir (1.4.2) - press Ctrl+C to exit (type h() ENTER for help)
> iex(1)> System.get_env("RECAPTCHA_PRIVATE_KEY")
> "some"
> iex(2)> Recaptcha.Config.get_env(:recaptcha, :secret)
> "some"

**Comment by denispeplin** [comment]
Now I understand my mistake. I don't have these env variables set. I've just put actual keys into `{:system, "RECAPTCHA_PUBLIC_KEY"}`, this is why library wasn't working for me.
Maybe `recaptcha` should raise error in this case.
