### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by sobolevn** [samueljseay/recaptcha#3]
Hey, thanks for the package!

But for me it's kind of suspicious to use a package without any tests. Maybe you need any help implementing them?

**Comment by JustMikey** [comment]
Hi, I still haven't finished with the second version but I will probably have some time this week and once I am done with that, we can cover everything with tests.

**Comment by sobolevn** [comment]
@JustMikey how's the progress going? 

I would be glad to help you If you open some specific issues.

**Comment by JustMikey** [comment]
@sobolevn Hi, everything will be done tomorrow by evening.

**Comment by JustMikey** [comment]
@sobolevn Hi, do you have any suggestions on how to test `verify/2` and `render_widget/1`? I have some ideas but those are not very neat so I wonder what you have on mind?

**Comment by sobolevn** [comment]
@JustMikey sorry, didn't have the time yesterday.  Today I have started with the `coverage` tool.

I have several questions/remarks:

1. I totally agree with you: `HTTPoison` should be an abstract part (also I would not expect `verify/2` to raise an exception on `HTTPoison.post!`). 
2. Any reason why `config :recaptcha, :api_config` is followed by a `%{}` and not `Keyword`? 
3. `request_body/3` seems a little bit harsh, I guess it could be refactored to be more good-looking.
4. Codestyle. Do you like tools like `dogma` or `credo`?

Great work already!

**Comment by samueljseay** [comment]
Closing this because much of it is duplicated in #2
