### ISSUE TITLE
Mock tests

### ISSUE THREAD

**Issue by thiamsantos** [samueljseay/recaptcha#36]
First of all, thanks for the incredible library!

What is the best way to mock the lib in order to prevent the requests to google and have an precise behaviour? What are your suggestions? Thanks in advance.

**Comment by sobolevn** [comment]
Thank you for using it! I like to do something like this: http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/

**Comment by samueljseay** [comment]
Seems like this is solved. Feel free to reopen if you have further questions :slightly_smiling_face:
