### ISSUE TITLE
Release 2.2.2

### ISSUE THREAD

**Issue by jeffjewiss** [samueljseay/recaptcha#39]
Hi, could you please release master as `v2.2.2`?

I'm currently having trouble installing this package due to #37, which has been resolved, but not yet released. Thanks!

**Comment by sobolevn** [comment]
Only @samueljseay can release.

**Comment by samueljseay** [comment]
Sorry folks, haven't had as much time to look at this project lately. @sobolevn can you confirm whether your github email would be suitable to add as owner in hex so you can also release?

**Comment by samueljseay** [comment]
I've released `2.2.2`

**Comment by sobolevn** [comment]
@samueljseay yeas, my github email is fine. Here's my hex account: https://hex.pm/users/sobolevn

**Comment by jeffjewiss** [comment]
@samueljseay thank you!
