### ISSUE TITLE
Script is blocking

### ISSUE THREAD

**Issue by matthijsgroen** [samueljseay/recaptcha#42]
https://github.com/samueljseay/recaptcha/blob/854e85b17cf2753b1270263f582a1ea5662cd16a/lib/template.html.eex#L1

Async and defer attributes were removed from the script tag in #41

**Comment by sobolevn** [comment]
@matthijsgroen can you please send a PR with the fix?

**Comment by matthijsgroen** [comment]
I can, I will need to investigate the possible consequences to the execute statement in the invisible implementation first
