### ISSUE TITLE
Release new version to hex.pm

### ISSUE THREAD

**Issue by luc-tielen** [samueljseay/recaptcha#44]
Hi, 

Could you increase the version (2.3?) in mix.exs + release to hex.pm?
Currently we depend on a fork of this library, would be nice if we could just use hex.
Thanks!

**Comment by sobolevn** [comment]
Yeap, that's on my roadmap. I will release it till weekends. 
Thanks for the reminder.

**Comment by luc-tielen** [comment]
Ok, thanks a lot 😄 !

**Comment by luc-tielen** [comment]
Great, thanks!
