### ISSUE TITLE
function nil.decode/1 is undefined

### ISSUE THREAD

**Issue by tporto** [samueljseay/recaptcha#52]
`json = Application.get_env(:recaptcha, :json_library)

    result =

      with {:ok, response} <-

             HTTPoison.post(url, body, @headers, timeout: timeout),

           {:ok, data} <- json.decode(response.body) do

        {:ok, data}

      end

    case result do

      {:ok, data} -> {:ok, data}`

**Comment by MyNameIsURL** [comment]
@tporto The issue is Jason isn't set as the default (even though the Readme says otherwise). So you need to explicitly set your json_library in your config like so

```
 config :recaptcha,
    public_key: {:system, "RECAPTCHA_PUBLIC_KEY"},
    secret: {:system, "RECAPTCHA_PRIVATE_KEY"},
    json_library: Jason
```

**Comment by sobolevn** [comment]
Hm, it should be set as a default. That's a bug. And PRs are more than welcome! 👍

**Comment by MyNameIsURL** [comment]
@sobolevn Awesome, I'll open a PR
