### ISSUE TITLE
recaptcha (version 3.0.0) requires ~> 3.1.0 or ~> 2.2.0 or ~> 1.5.2

### ISSUE THREAD

**Issue by justinbkay** [samueljseay/recaptcha#54]
Does this project need a release bump?  I'm in a dependency "situation" because of the version of Poison that it requires, but looking in master, it doesn't appear to require Poison at all.  This leads me to believe that might need a new release that drops the dependency on Poison.

**Comment by tomciopp** [comment]
Having the same issue, bumping for attention

**Comment by sobolevn** [comment]
@samueljseay can you please have a look at this?

**Comment by tomciopp** [comment]
@samueljseay Bumping again for attention.

**Comment by samueljseay** [comment]
Hey folks I'm not actively working on this right now sorry. @sobolevn You also have rights and permissions to get this across the line right?

**Comment by tomciopp** [comment]
@samueljseay @sobolevn Do you need someone else to help out with the backlog? I would be happy to assist.

**Comment by samueljseay** [comment]
@tomciopp yes please! I'd love to work on this more actively but I unfortunately don't do elixir much currently, I can however do my best to be available to review PRs.

**Comment by tomciopp** [comment]
@samueljseay Would be glad to help out in anyway possible. Can we first get a point release of what is currently is master?

**Comment by samueljseay** [comment]
I notice that @sobolevn put out a release a few days ago. Is this solved? Sorry again that I've been so unresponsive.

**Comment by samueljseay** [comment]
@tomciopp I'm sorry I've been so unresponsive. Tentatively I might have a bit more time for this project in the coming months. I've released a 3.1.0 with everything from master. I'll close this for now but please reopen if any issue still exists.
