### ISSUE TITLE
Making validation call configurable

### ISSUE THREAD

**Issue by sobolevn** [samueljseay/recaptcha#6]
Things I suggest:

1. Use `:hackney` as a default `HTTP`-server
2. Create new `macro` to handle the verifications (`Recaptcha.Validator`)
3. Rewrite `verify/2` to works with tuples `{:ok, _}` and `{:error, _}` and not with bang versions.
4. Create an `overridable` function to be used like so:

```elixir
defmodule MyApp.RecaptchaValidator do
  use Recaptcha.Validator
 
  def verify_request(verify_url, body, headers) do
    # Old signature:
    # HTTPoison.post!(@site_verify_url, body, headers, timeout: timeout)
    {:ok, response} = MyHttpServer.post(verify_url, body, headers)
  end
end
```

And then test all the things.

What do you think of it?

**Comment by JustMikey** [comment]
1) Why `hackney`? `Httpoison` uses it under the hood anyway.
3) Yeah, we could do that
4) Could you please explain what is the use case for the overridable function?

**Comment by sobolevn** [comment]
`hackney` is faster, as I see a lot of projects using it directly. And since we don't have any complicated logic, this might be a good usecase with no disadvantages.

Today the idea with custom verification function does not seem very good to me. At first I thought that it is nice and clean solution. But now it seems as overcomplicated peace. Now I think that just `hackney` is fine.

p.s. Do you live in Moscow? We are scheduling [a meetup in Moscow](https://github.com/elixir-lang-moscow/events/issues/1) and looking for speakers. Contact me by email, if it is possible and you are interested.

**Comment by JustMikey** [comment]
As far as I understand,  `httpoison` is pretty much a wrapper around `hackney` so the performance is probably not gonna improve significantly but we'll have to dive into Erlang. To my knowledge `hackney` is faster than `ibrowse`,  which is used by `httpotion` so if we used `httpotion` that would make sense. We could use `hackney` only as a way to get rid of `httpoison` as a dependency though.

**Comment by samueljseay** [comment]
So, because this lib doesn't seem to get much attention at the moment, I'm working on building something like this myself as another lib with tests etc. (coming soon 😄) @JustMikey I'd be happy to discuss whether you'd want to hand over this repo to someone with a bit more time (or not if you're happy with there being another recaptcha lib out there, I don't really mind)

@sobolevn I'll be implementing simple ok/error tuples for responses and no bang version.

I looked at implementing my version with hackney, but honestly I don't think its worth it. For example here's the HttpPoison wrapper around hackneys request and body processing: https://github.com/edgurgel/httpoison/blob/master/lib/httpoison/base.ex#L410 If I was to use hackney I'd probably end up reimplementing this (at minimum), and for what benefit? reducing dependencies isn't a good reason to copy paste code in this case I don't think. I'm glad I investigated this but.. yeah I don't think its worthwhile.

**Comment by sobolevn** [comment]
@samueljseay thanks for the feedback! 

I have spent a little bit of time to play around `hackney` and `httpoison`, I do also agree with you: there's no need in working with `hackney` directly. 

Considering new repo, is it really worth it? Maybe we should cooperate to make this one better? The `v2` branch has just a little bit of work to be done. I would really appreciate your help on this one! You can count on me on easy and quick tasks.

**Comment by JustMikey** [comment]
@samueljseay Yeah I would be glad to hand it over and I apologize for irresponsibility.

**Comment by samueljseay** [comment]
@JustMikey no worries at all, I totally understand things get busy! Thanks for the transfer! Happy to continue making this little lib great. :smile:

@sobolevn so I got ahead of myself and rewrote the verification stuff. and some of what I've done seems similar to the v2 branch. How set are we on being strictly backwards compatible?

For example I've made remote_ip optional in my rewrite.. Would it be worth having a look at what I've got in a PR and discussing?

One other thing that bugs me is the template side of this library.. it almost feels like the templates should be a separate dependency... e.g. something like recaptcha_phoenix or something?

**Comment by sobolevn** [comment]
@samueljseay ok, looking forward to see your changes!

Templates is a good question, why do you think it should be a separate project? 

When it comes to templates, `recaptcha` widget is suggested to be used like: `<%= raw Recaptcha.display %>`, I guess the main problem is here. Since `raw/1` is a part of `Phonix.HTML`. So, I guess, the docs should cover the case with `phoenix` and the case with just `eex`.

**Comment by samueljseay** [comment]
@sobolevn I guess I just feel like not everyone using this lib is going to have any need for the templating side of it (for my current use of it I don't use the template stuff at all).

I feel like providing templating and mentioning "Phoenix" will attract some developers and put others off.

Having said all that, if you feel strongly about keeping the templating in the library I'd be ok with that and maybe we could remove all mention of Phoenix and cover the non-Phoenix case for rendering the template?

I'd probably also be keen to move the templating into a separate module like Recaptcha.Template or something?

**Comment by samueljseay** [comment]
@JustMikey I was wondering if you could add me as a package owner on Hex? https://hex.pm/docs/tasks#hex_owner looks like its fairly straightforward. samueljseay@gmail.com

**Comment by samueljseay** [comment]
hey @JustMikey pinging you, hoping you'll get this, I haven't found any other way to get in touch with you. 

I was wondering if you could add me as a package owner on Hex?https://hex.pm/docs/tasks#hex_owner my email is: samueljseay@gmail.com

**Comment by JustMikey** [comment]
@samueljseay Hi, sure, I will do it tonight. Sorry for the long reply.

**Comment by JustMikey** [comment]
Done. Sorry it took me again so much time, had problems with the internet connection.

**Comment by samueljseay** [comment]
No worries! Thanks so much @JustMikey . I'll be able to do a new release very soon! :clap:

**Comment by sobolevn** [comment]
@samueljseay @JustMikey thank you guys for a new release!
Will test it out on [this project](https://github.com/elixir-lang-moscow/site)
