### ISSUE TITLE
Bump dependencies

### ISSUE THREAD

**Issue by hickscorp** [samueljseay/recaptcha#62]
It seems that `recaptcha` is using a fairly outdated version of `poison`. It would be really good if it could support more recent versions, because recent versions of dependencies like `poison` are used in many other packages, making it a hard choice to make to pick `recaptcha`.

**Comment by samueljseay** [comment]
Yes that would be great. I'm sorry I don't have the bandwidth to fix that right now (I'm not actively developing this), but I welcome PRs and I'd be happy to review submissions.

**Comment by samueljseay** [comment]
I believe this should be resolved now since the library lets you use Jason instead. Please reopen if you feel I've missed something, I'm still catching back up on this project.
