### ISSUE TITLE
Json parser issue in version 3.0.0

### ISSUE THREAD

**Issue by luistorres** [samueljseay/recaptcha#64]
I don't know exactly how it is happening yet, but on version 3.0.0 when json parser was updated to Jason, it doesn't seem to be picked up by the configuration, as i get this error:
```
 ** (UndefinedFunctionError) function nil.decode/1 is undefined
        nil.decode("{\n  \"success\": false,\n  \"error-codes\": [\n    \"timeout-or-duplicate\"\n  ]\n}")
        (recaptcha 3.0.0) lib/recaptcha/http.ex:48: Recaptcha.Http.request_verification/2
        (recaptcha 3.0.0) lib/recaptcha.ex:31: Recaptcha.verify/2
```

I'm able to run it without issues if I still add this line in my config file as it was previously recommended:
`config :recaptcha, :json_library, Jason`

**Comment by samueljseay** [comment]
I've just published a release of latest master as 3.1.0, I believe this should be fixed by #53 but please reopen if you experience more problems.

the core of the issue was that there was no default fallback when the config wasn't set.
