### ISSUE TITLE
Dependencies resolution error

### ISSUE THREAD

**Issue by sobolevn** [samueljseay/recaptcha#9]
I am upgrading from the first version of `recaptcha`, faced this issue:

> [12:43:19] sobolev :: MacBook-Pro-Nikita  ➜  Documents/elixir/elixir_lang_moscow ‹master› » mix deps.get
> A new Hex version is available (0.13.0), please update with `mix local.hex`
> Running dependency resolution
> 
> Failed to use "poison" (versions 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 2.0.0, 2.0.1, 2.1.0, 2.2.0) because
>   arc (version 0.5.3) requires ~> 1.2 or ~> 2.0
>   dogma (version 0.1.7) requires >= 1.0.0
>   ecto (version 1.1.9) requires ~> 1.0 or ~> 2.0
>   ex_aws (version 0.4.19) requires ~> 1.2 or ~> 2.0
>   guardian (version 0.10.1) requires ~> 1.5
>   phoenix (version 1.1.6) requires ~> 1.5 or ~> 2.0
>   phoenix_ecto (version 2.0.2) requires ~> 1.3 or ~> 2.0
>   swoosh (version 0.4.0) requires ~> 1.5 or ~> 2.0
> 
> Failed to use "poison" (versions 1.5.0 to 1.5.2) because
>   arc (version 0.5.3) requires ~> 1.2 or ~> 2.0
>   dogma (version 0.1.7) requires >= 1.0.0
>   ecto (version 1.1.9) requires ~> 1.0 or ~> 2.0
>   ex_aws (version 0.4.19) requires ~> 1.2 or ~> 2.0
>   guardian (version 0.10.1) requires ~> 1.5
>   phoenix (version 1.1.6) requires ~> 1.5 or ~> 2.0
>   phoenix_ecto (version 2.0.2) requires ~> 1.3 or ~> 2.0
>   #! recaptcha (version 2.0.0) requires ~> 2.0
>   swoosh (version 0.4.0) requires ~> 1.5 or ~> 2.0
> 
> ** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock)

Poison version from the `mix.lock`:

> "poison": {:hex, :poison, "1.5.2", "560bdfb7449e3ddd23a096929fb9fc2122f709bcc758b2d5d5a5c7d0ea848910", [:mix], []},

I guess this issue can be solved by editing `poison` dependency string to something like: `{:poison, "~> 1.5 or ~> 2.0"},`

**Comment by samueljseay** [comment]
Hmm. ok thanks @sobolevn I'll take a look ASAP
